version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./pgdb/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./.env

  redis:
    image: redis:5
    restart: "on-failure"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ../redisdb:/var/lib/redis

#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/co
#    ports:
#      - "8000:8000"
#    env_file:
#      ./.env
#    depends_on:
#      - "db"