# Generated by Django 3.2.12 on 2022-03-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.PositiveIntegerField()),
                ('website_title', models.CharField(blank=True, default='Cansat - Teknofest', max_length=50)),
            ],
        ),
    ]
