# Generated by Django 3.2.12 on 2022-03-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_duration', models.PositiveIntegerField(blank=True, default=0.0)),
                ('number_of_telemetry_packets', models.PositiveIntegerField(blank=True, default=0.0)),
                ('battery_voltage', models.FloatField(blank=True, default=0.0)),
                ('altitude', models.FloatField(blank=True, default=0.0)),
                ('velocity', models.FloatField(blank=True, default=0.0)),
                ('no2_level_in_ppm', models.FloatField(blank=True, default=0.0)),
                ('no_level_in_ppm', models.FloatField(blank=True, default=0.0)),
                ('h2_level_in_ppm', models.FloatField(blank=True, default=0.0)),
                ('latitude', models.FloatField(blank=True, default=0.0)),
                ('longitude', models.FloatField(blank=True, default=0.0)),
                ('has_recording_started', models.BooleanField(blank=True, default=False)),
                ('departure_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_readings', to='core.setting')),
            ],
            options={
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ('-created_at',),
            },
        ),
    ]
