# Generated by Django 3.2.12 on 2022-03-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensorreading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='no_level_in_ppm',
            new_name='co_level_in_ppm',
        ),
    ]
