# Generated by Django 3.2.12 on 2022-03-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_no_level_in_ppm_sensorreading_co_level_in_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
