# Generated by Django 3.2.12 on 2022-04-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_no2_level_in_ppm_sensorreading_n2_level_in_ppm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='latitude',
            new_name='gps_altitude',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='longitude',
            new_name='gps_latitude',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='gps_longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
