# Generated by Django 3.2.13 on 2022-05-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220425_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='n2_level_in_ppm',
            new_name='no2_level_in_ppm',
        ),
    ]
