# Generated by Django 3.2.13 on 2022-05-15 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_n2_level_in_ppm_sensorreading_no2_level_in_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='enable_sensor_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sensor_readings', to='core.setting'),
        ),
    ]
