# Generated by Django 3.2.13 on 2022-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220515_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='distance_to_ground',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
