# Generated by Django 3.2.15 on 2022-10-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sensorreading_distance_to_ground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='has_recording_started',
        ),
    ]
